// buyer action type
export const FETCH_BUYERS_REQUEST = 'FETCH_BUYERS_REQUEST';
export const FETCH_BUYERS_SUCCESS = 'FETCH_BUYERS_SUCCESS';
export const FETCH_BUYERS_ERROR = 'FETCH_BUYERS_ERROR';

export const FETCH_BUYER_BY_ID_REQUEST = 'FETCH_BUYER_BY_ID_REQUEST';
export const FETCH_BUYER_BY_ID_SUCCESS = 'FETCH_BUYER_BY_ID_SUCCESS';
export const FETCH_BUYER_BY_ID_ERROR = 'FETCH_BUYER_BY_ID_ERROR';

export const FETCH_GIVEN_TENDERS_REQUEST = 'FETCH_GIVEN_TENDERS_REQUEST';
export const FETCH_GIVEN_TENDERS_SUCCESS = 'FETCH_GIVEN_TENDERS_SUCCESS';
export const FETCH_GIVEN_TENDERS_ERROR = 'FETCH_GIVEN_TENDERS_ERROR';
