// seller action type
export const FETCH_SELLERS_REQUEST = 'FETCH_SELLERS_REQUEST';
export const FETCH_SELLERS_SUCCESS = 'FETCH_SELLERS_SUCCESS';
export const FETCH_SELLERS_ERROR = 'FETCH_SELLERS_ERROR';

export const FETCH_SELLER_BY_ID_REQUEST = 'FETCH_SELLER_BY_ID_REQUEST';
export const FETCH_SELLER_BY_ID_SUCCESS = 'FETCH_SELLER_BY_ID_SUCCESS';
export const FETCH_SELLER_BY_ID_ERROR = 'FETCH_SELLER_BY_ID_ERROR';

export const FETCH_PLATFORMS_REQUEST = 'FETCH_PLATFORMS_REQUEST';
export const FETCH_PLATFORMS_SUCCESS = 'FETCH_PLATFORMS_SUCCESS';
export const FETCH_PLATFORMS_ERROR = 'FETCH_PLATFORMS_ERROR';

export const FETCH_PLATFORM_BY_ID_REQUEST = 'FETCH_PLATFORM_BY_ID_REQUEST';
export const FETCH_PLATFORM_BY_ID_SUCCESS = 'FETCH_PLATFORM_BY_ID_SUCCESS';
export const FETCH_PLATFORM_BY_ID_ERROR = 'FETCH_PLATFORM_BY_ID_ERROR';

export const FETCH_TENDER_REQUESTS = 'FETCH_TENDER_REQUESTS';
export const FETCH_TENDER_SUCCESS = 'FETCH_TENDER_SUCCESS';
export const FETCH_TENDER_ERROR = 'FETCH_TENDER_ERROR';
